from enum import Enum


class ProductType(str, Enum):
    PERSONAL_FINANCE = "PERSONAL_FINANCE"
    AUTO_FINANCE = "AUTO_FINANCE"


class DocumentType(str, Enum):
    ID_DOCUMENT = "ID_DOCUMENT"
    SALARY_CERTIFICATE = "SALARY_CERTIFICATE"
    BANK_STATEMENT = "BANK_STATEMENT"
    VEHICLE_QUOTE = "VEHICLE_QUOTE"


class ValidationOutcome(str, Enum):
    HARD_BREACH = "HARD_BREACH"
    SOFT_MISMATCH = "SOFT_MISMATCH"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    PASSED = "PASSED"


class Recommendation(str, Enum):
    APPROVE = "APPROVE"
    HOLD = "HOLD"
    DECLINE = "DECLINE"


class CaseStatus(str, Enum):
    RECEIVED = "RECEIVED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    DEAD_LETTERED = "DEAD_LETTERED"


class DocumentStatus(str, Enum):
    PENDING = "PENDING"
    FETCHED = "FETCHED"
    VERIFIED = "VERIFIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    EXTRACTED = "EXTRACTED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"


class EDWStatus(str, Enum):
    STAGED = "STAGED"
    EXPORTED = "EXPORTED"
    EXPORT_FAILED = "EXPORT_FAILED"
