"""align_schema_with_design_spec

Revision ID: 1fe5657ce65e
Revises: 001
Create Date: 2026-05-01 07:25:33.907265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fe5657ce65e'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('manual_review_required', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['application_case.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('dms_artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('dms_document_id', sa.String(length=200), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interacted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['application_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dms_artifact_case_id'), 'dms_artifact', ['case_id'], unique=False)
    op.create_table('processing_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['application_case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_job_case_id'), 'processing_job', ['case_id'], unique=False)
    op.create_index('ix_processing_job_case_type_status', 'processing_job', ['case_id', 'job_type', 'status'], unique=False)
    op.add_column('application_case', sa.Column('manual_review_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('application_case', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('application_case', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('application_case', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ac_supervisor_id'), table_name='application_case')
    op.drop_index(op.f('ix_ac_validator_id'), table_name='application_case')
    op.create_index('ix_application_case_status_created', 'application_case', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_application_case_supervisor_id'), 'application_case', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_application_case_validator_id'), 'application_case', ['validator_id'], unique=False)
    op.add_column('audit_event', sa.Column('actor', sa.String(length=100), nullable=True))
    op.alter_column('audit_event', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_event_case_id'), 'audit_event', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_event_occurred_at'), 'audit_event', ['occurred_at'], unique=False)
    op.add_column('case_document', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('case_document', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('case_document', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_document', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cd_case_id'), table_name='case_document')
    op.create_index(op.f('ix_case_document_case_id'), 'case_document', ['case_id'], unique=False)
    op.add_column('case_report', sa.Column('html_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('case_report', sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('case_report', sa.Column('pdf_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('case_report', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_report', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('dead_letter_event', sa.Column('case_id', sa.UUID(), nullable=True))
    op.add_column('dead_letter_event', sa.Column('stack_trace', sa.Text(), nullable=True))
    op.add_column('dead_letter_event', sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('dead_letter_event', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_dle_application_id'), table_name='dead_letter_event')
    op.create_index(op.f('ix_dead_letter_event_application_id'), 'dead_letter_event', ['application_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_event_case_id'), 'dead_letter_event', ['case_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_event_event_id'), 'dead_letter_event', ['event_id'], unique=False)
    op.create_foreign_key(None, 'dead_letter_event', 'application_case', ['case_id'], ['id'])
    op.add_column('edw_staging', sa.Column('staged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('edw_staging', sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('edw_staging', sa.Column('export_error', sa.Text(), nullable=True))
    op.alter_column('edw_staging', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('edw_staging', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('inbound_application_event', sa.Column('product_type', sa.String(length=50), nullable=True))
    op.add_column('inbound_application_event', sa.Column('status', sa.String(length=50), nullable=False, server_default=sa.text("'RECEIVED'")))
    op.add_column('inbound_application_event', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('inbound_application_event', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_iae_application_id'), table_name='inbound_application_event')
    op.create_index(op.f('ix_inbound_application_event_application_id'), 'inbound_application_event', ['application_id'], unique=False)
    op.add_column('stage_output_version', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('stage_output_version', sa.Column('validation_error', sa.Text(), nullable=True))
    op.add_column('stage_output_version', sa.Column('raw_ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('stage_output_version', sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_stage_output_version_case_document_id'), 'stage_output_version', ['case_document_id'], unique=False)
    op.drop_column('stage_output_version', 'created_at')
    op.add_column('validation_result', sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validation_result', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validation_result', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('validation_result', sa.Column('manual_review_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('validation_result', sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_vr_case_id'), table_name='validation_result')
    op.drop_index(op.f('ix_vr_outcome'), table_name='validation_result')
    op.create_index(op.f('ix_validation_result_case_id'), 'validation_result', ['case_id'], unique=False)
    op.create_index('ix_validation_result_case_outcome', 'validation_result', ['case_id', 'outcome'], unique=False)
    op.drop_column('validation_result', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_result', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index('ix_validation_result_case_outcome', table_name='validation_result')
    op.drop_index(op.f('ix_validation_result_case_id'), table_name='validation_result')
    op.create_index(op.f('ix_vr_outcome'), 'validation_result', ['outcome'], unique=False)
    op.create_index(op.f('ix_vr_case_id'), 'validation_result', ['case_id'], unique=False)
    op.drop_column('validation_result', 'evaluated_at')
    op.drop_column('validation_result', 'manual_review_required')
    op.drop_column('validation_result', 'confidence')
    op.drop_column('validation_result', 'details')
    op.drop_column('validation_result', 'input_data')
    op.add_column('stage_output_version', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stage_output_version_case_document_id'), table_name='stage_output_version')
    op.drop_column('stage_output_version', 'extracted_at')
    op.drop_column('stage_output_version', 'raw_ai_response')
    op.drop_column('stage_output_version', 'validation_error')
    op.drop_column('stage_output_version', 'is_valid')
    op.drop_index(op.f('ix_inbound_application_event_application_id'), table_name='inbound_application_event')
    op.create_index(op.f('ix_iae_application_id'), 'inbound_application_event', ['application_id'], unique=False)
    op.alter_column('inbound_application_event', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('inbound_application_event', 'updated_at')
    op.drop_column('inbound_application_event', 'status')
    op.drop_column('inbound_application_event', 'product_type')
    op.alter_column('edw_staging', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('edw_staging', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('edw_staging', 'export_error')
    op.drop_column('edw_staging', 'exported_at')
    op.drop_column('edw_staging', 'staged_at')
    op.drop_constraint(None, 'dead_letter_event', type_='foreignkey')
    op.drop_index(op.f('ix_dead_letter_event_event_id'), table_name='dead_letter_event')
    op.drop_index(op.f('ix_dead_letter_event_case_id'), table_name='dead_letter_event')
    op.drop_index(op.f('ix_dead_letter_event_application_id'), table_name='dead_letter_event')
    op.create_index(op.f('ix_dle_application_id'), 'dead_letter_event', ['application_id'], unique=False)
    op.alter_column('dead_letter_event', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('dead_letter_event', 'replayed_at')
    op.drop_column('dead_letter_event', 'stack_trace')
    op.drop_column('dead_letter_event', 'case_id')
    op.alter_column('case_report', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_report', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('case_report', 'pdf_uploaded_at')
    op.drop_column('case_report', 'pdf_generated_at')
    op.drop_column('case_report', 'html_generated_at')
    op.drop_index(op.f('ix_case_document_case_id'), table_name='case_document')
    op.create_index(op.f('ix_cd_case_id'), 'case_document', ['case_id'], unique=False)
    op.alter_column('case_document', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_document', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('case_document', 'verified_at')
    op.drop_column('case_document', 'fetched_at')
    op.drop_index(op.f('ix_audit_event_occurred_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_case_id'), table_name='audit_event')
    op.alter_column('audit_event', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('audit_event', 'actor')
    op.drop_index(op.f('ix_application_case_validator_id'), table_name='application_case')
    op.drop_index(op.f('ix_application_case_supervisor_id'), table_name='application_case')
    op.drop_index('ix_application_case_status_created', table_name='application_case')
    op.create_index(op.f('ix_ac_validator_id'), 'application_case', ['validator_id'], unique=False)
    op.create_index(op.f('ix_ac_supervisor_id'), 'application_case', ['supervisor_id'], unique=False)
    op.alter_column('application_case', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('application_case', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('application_case', 'completed_at')
    op.drop_column('application_case', 'manual_review_required')
    op.drop_index('ix_processing_job_case_type_status', table_name='processing_job')
    op.drop_index(op.f('ix_processing_job_case_id'), table_name='processing_job')
    op.drop_table('processing_job')
    op.drop_index(op.f('ix_dms_artifact_case_id'), table_name='dms_artifact')
    op.drop_table('dms_artifact')
    op.drop_table('case_result')
    # ### end Alembic commands ###
