"""terminal_state_fks_audit_partitioning

Revision ID: 9fa2b5c9c2c8
Revises: 1fe5657ce65e
Create Date: 2026-05-02 07:30:20.506130

Adds (autogenerated):
  - error_detail TEXT on application_case, case_document, case_report
  - FK application_case.event_id  -> inbound_application_event.event_id
  - FK dead_letter_event.event_id -> inbound_application_event.event_id
  - drops redundant validation_result.input_data and .details JSONB columns

Adds (manual — autogenerate cannot derive these):
  - data migration: legacy CaseStatus / CaseReportStatus values mapped to
    the new enum values
  - orphan cleanup so the new FKs can be created safely
  - converts audit_event to a monthly RANGE-partitioned table
"""
from datetime import date
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fa2b5c9c2c8'
down_revision: Union[str, None] = '1fe5657ce65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --------------------------------------------------------------------- #
#  Helpers (manual)                                                       #
# --------------------------------------------------------------------- #


def _create_monthly_partition(parent: str, year: int, month: int) -> None:
    name = f"{parent}_{year:04d}_{month:02d}"
    start = date(year, month, 1).isoformat()
    end_year = year + 1 if month == 12 else year
    end_month = 1 if month == 12 else month + 1
    end = date(end_year, end_month, 1).isoformat()
    op.execute(
        f"CREATE TABLE IF NOT EXISTS {name} PARTITION OF {parent} "
        f"FOR VALUES FROM ('{start}') TO ('{end}');"
    )


def upgrade() -> None:
    # --- Manual: backfill legacy status values before any FK / column work --
    op.execute("UPDATE application_case SET status = 'CREATED' WHERE status = 'RECEIVED';")
    op.execute("UPDATE application_case SET status = 'FAILED'  WHERE status = 'DEAD_LETTERED';")
    op.execute("UPDATE case_report      SET status = 'PENDING'  WHERE status = 'GENERATING';")
    op.execute("UPDATE case_report      SET status = 'UPLOADED' WHERE status = 'COMPLETED';")
    op.execute("UPDATE case_report      SET status = 'FAILED'   WHERE status = 'UPLOAD_FAILED';")

    # --- Manual: orphan cleanup so the new FKs can be created --------------
    op.execute(
        "DELETE FROM application_case ac "
        "WHERE NOT EXISTS ("
        "  SELECT 1 FROM inbound_application_event iae "
        "  WHERE iae.event_id = ac.event_id"
        ");"
    )
    op.execute(
        "UPDATE dead_letter_event dle SET event_id = NULL "
        "WHERE event_id IS NOT NULL "
        "AND NOT EXISTS ("
        "  SELECT 1 FROM inbound_application_event iae "
        "  WHERE iae.event_id = dle.event_id"
        ");"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_case', sa.Column('error_detail', sa.Text(), nullable=True))
    op.create_foreign_key('fk_application_case_event_id', 'application_case', 'inbound_application_event', ['event_id'], ['event_id'])
    op.add_column('case_document', sa.Column('error_detail', sa.Text(), nullable=True))
    op.add_column('case_report', sa.Column('error_detail', sa.Text(), nullable=True))
    op.create_foreign_key('fk_dead_letter_event_id', 'dead_letter_event', 'inbound_application_event', ['event_id'], ['event_id'])
    op.drop_column('validation_result', 'details')
    op.drop_column('validation_result', 'input_data')
    # ### end Alembic commands ###

    # --- Manual: convert audit_event to a partitioned table ----------------
    # PG native partitioning needs the partition key inside the PK, so the
    # cleanest path is rename → recreate partitioned → copy data → drop old.
    op.execute("ALTER TABLE audit_event RENAME TO audit_event_old;")
    # Indexes follow the table on rename but keep their original names; rename
    # them aside so the partitioned table can re-create canonical names.
    op.execute("ALTER INDEX ix_audit_event_case_id     RENAME TO ix_audit_event_case_id_old;")
    op.execute("ALTER INDEX ix_audit_event_occurred_at RENAME TO ix_audit_event_occurred_at_old;")
    op.execute("ALTER INDEX ix_audit_event_case_time   RENAME TO ix_audit_event_case_time_old;")
    op.execute(
        """
        CREATE TABLE audit_event (
            id              UUID NOT NULL,
            occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
            case_id         UUID,
            application_id  VARCHAR(100),
            event_type      VARCHAR(100) NOT NULL,
            actor           VARCHAR(100),
            detail          JSONB,
            PRIMARY KEY (id, occurred_at),
            FOREIGN KEY (case_id) REFERENCES application_case (id)
        ) PARTITION BY RANGE (occurred_at);
        """
    )
    op.execute("CREATE INDEX ix_audit_event_case_id     ON audit_event (case_id);")
    op.execute("CREATE INDEX ix_audit_event_occurred_at ON audit_event (occurred_at);")
    op.execute("CREATE INDEX ix_audit_event_case_time   ON audit_event (case_id, occurred_at);")

    # Monthly partitions covering existing data (from 2026-01) plus the next
    # 18 months. A scheduled maintenance job (pg_partman or equivalent) must
    # extend this window before the last partition fills up.
    today = date.today()
    cursor_year, cursor_month = 2026, 1
    end_total_months = today.year * 12 + today.month + 18
    while cursor_year * 12 + cursor_month <= end_total_months:
        _create_monthly_partition("audit_event", cursor_year, cursor_month)
        if cursor_month == 12:
            cursor_year += 1
            cursor_month = 1
        else:
            cursor_month += 1

    # Default partition catches anything outside the explicit ranges so a
    # missing future partition does not silently drop audit rows.
    op.execute(
        "CREATE TABLE IF NOT EXISTS audit_event_default "
        "PARTITION OF audit_event DEFAULT;"
    )

    op.execute(
        "INSERT INTO audit_event "
        "(id, occurred_at, case_id, application_id, event_type, actor, detail) "
        "SELECT id, occurred_at, case_id, application_id, event_type, actor, detail "
        "FROM audit_event_old;"
    )
    op.execute("DROP TABLE audit_event_old;")


def downgrade() -> None:
    # --- Manual: undo audit_event partitioning ----------------------------
    op.execute("ALTER TABLE audit_event RENAME TO audit_event_part;")
    op.execute(
        """
        CREATE TABLE audit_event (
            id              UUID PRIMARY KEY,
            case_id         UUID,
            application_id  VARCHAR(100),
            event_type      VARCHAR(100) NOT NULL,
            actor           VARCHAR(100),
            detail          JSONB,
            occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
            FOREIGN KEY (case_id) REFERENCES application_case (id)
        );
        """
    )
    op.execute("CREATE INDEX ix_audit_event_case_id     ON audit_event (case_id);")
    op.execute("CREATE INDEX ix_audit_event_occurred_at ON audit_event (occurred_at);")
    op.execute("CREATE INDEX ix_audit_event_case_time   ON audit_event (case_id, occurred_at);")
    op.execute(
        "INSERT INTO audit_event "
        "(id, occurred_at, case_id, application_id, event_type, actor, detail) "
        "SELECT id, occurred_at, case_id, application_id, event_type, actor, detail "
        "FROM audit_event_part;"
    )
    op.execute("DROP TABLE audit_event_part CASCADE;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_result', sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('validation_result', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('fk_dead_letter_event_id', 'dead_letter_event', type_='foreignkey')
    op.drop_column('case_report', 'error_detail')
    op.drop_column('case_document', 'error_detail')
    op.drop_constraint('fk_application_case_event_id', 'application_case', type_='foreignkey')
    op.drop_column('application_case', 'error_detail')
    # ### end Alembic commands ###
